### ISSUE TITLE
Will not associate the last open window

### ISSUE THREAD

**Issue by fjqingyou** [icsharpcode/ilspy-vscode#32]
Decompile any Assembly, view any class, there will be Untitled1, Untitled2 window

Do not uninstall this Assembly, use Command+Q on Mac to exit vscode, and then re-open VSCode.

the original Untitled1 and Untitled2 are still there.

decompile any Assembly again, view any class. The Untitled3 and Untitled4 windows are opened.

Loop operation will open a new window infinitely

**Comment by jeremymeng** [comment]
It's tricky to get the behavior right

- The current behavior is due to how the `untitled:` scheme works in VS Code and we have no control over it.
- I have considered switching to `file:` scheme. But there are some issue with that: it can only opens existing files. We could create files in %temp% folder and use them. However, if users save the files, next time we use them we are overwriting the saved files and I don't think it's good.

**Comment by fjqingyou** [comment]
can you usin cehce file map? 
temp file has map file? save file check it ?if it's temp file so  show confirm view , user can select save as new path?

**Comment by Rpinski** [comment]
Also see #47

Since we have stopped using temporary files with 3c1a220fcb0944cd7dfc2224be3180ef5ae58a0b, all those problems with re-opened files after startup should have gone since 0.12 release.

Please open a new issue if still anything strange happens.
